//! OWL/XML Vocabulary — typed enum of all OWL/XML element names.
//!
//! Equivalent to OWL API v5's `OWLXMLVocabulary` enum.
//! Each variant maps to its OWL/XML short name used in serialization.

use crate::ontology::IRI;

/// All 105 OWL/XML element names as defined by the OWL 2 specification.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum OwlXmlElement {
    // Root
    Ontology,
    // Entity declarations
    Class,
    ObjectProperty,
    DataProperty,
    AnnotationProperty,
    NamedIndividual,
    Datatype,
    AnonymousIndividual,
    // Class Expression Constructors
    ObjectIntersectionOf,
    ObjectUnionOf,
    ObjectComplementOf,
    ObjectOneOf,
    // Object Property Restrictions
    ObjectSomeValuesFrom,
    ObjectAllValuesFrom,
    ObjectHasValue,
    ObjectHasSelf,
    ObjectMinCardinality,
    ObjectMaxCardinality,
    ObjectExactCardinality,
    // Data Property Restrictions
    DataSomeValuesFrom,
    DataAllValuesFrom,
    DataHasValue,
    DataMinCardinality,
    DataMaxCardinality,
    DataExactCardinality,
    // Data Ranges
    DataComplementOf,
    DataOneOf,
    DataIntersectionOf,
    DataUnionOf,
    DatatypeRestriction,
    FacetRestriction,
    // Class Axioms
    SubClassOf,
    EquivalentClasses,
    DisjointClasses,
    DisjointUnion,
    // Object Property Axioms
    SubObjectPropertyOf,
    ObjectPropertyChain,
    EquivalentObjectProperties,
    DisjointObjectProperties,
    InverseObjectProperties,
    ObjectPropertyDomain,
    ObjectPropertyRange,
    FunctionalObjectProperty,
    InverseFunctionalObjectProperty,
    SymmetricObjectProperty,
    AsymmetricObjectProperty,
    ReflexiveObjectProperty,
    IrreflexiveObjectProperty,
    TransitiveObjectProperty,
    // Data Property Axioms
    SubDataPropertyOf,
    EquivalentDataProperties,
    DisjointDataProperties,
    DataPropertyDomain,
    DataPropertyRange,
    FunctionalDataProperty,
    // Individual Axioms
    SameIndividual,
    DifferentIndividuals,
    ClassAssertion,
    ObjectPropertyAssertion,
    DataPropertyAssertion,
    NegativeObjectPropertyAssertion,
    NegativeDataPropertyAssertion,
    // Annotation Axioms
    AnnotationAssertion,
    SubAnnotationPropertyOf,
    AnnotationPropertyDomain,
    AnnotationPropertyRange,
    // Other Axioms
    Declaration,
    HasKey,
    DatatypeDefinition,
    // Common Elements
    Literal,
    IRI,
    AbbreviatedIRI,
    Annotation,
    Import,
    Prefix,
    Name,
    Cardinality,
    NodeID,
    AnnotationURI,
    DatatypeIRI,
    Facet,
    // SWRL / Rules
    DLSafeRule,
    Body,
    Head,
    ClassAtom,
    DataRangeAtom,
    ObjectPropertyAtom,
    DataPropertyAtom,
    BuiltInAtom,
    SameIndividualAtom,
    DifferentIndividualsAtom,
    Variable,
    DescriptionGraphRule,
}

impl OwlXmlElement {
    /// Get the OWL/XML short name for this element.
    #[must_use]
    pub fn short_name(&self) -> &'static str {
        match self {
            Self::Ontology => "Ontology",
            Self::Class => "Class",
            Self::ObjectProperty => "ObjectProperty",
            Self::DataProperty => "DataProperty",
            Self::AnnotationProperty => "AnnotationProperty",
            Self::NamedIndividual => "NamedIndividual",
            Self::Datatype => "Datatype",
            Self::AnonymousIndividual => "AnonymousIndividual",
            Self::ObjectIntersectionOf => "ObjectIntersectionOf",
            Self::ObjectUnionOf => "ObjectUnionOf",
            Self::ObjectComplementOf => "ObjectComplementOf",
            Self::ObjectOneOf => "ObjectOneOf",
            Self::ObjectSomeValuesFrom => "ObjectSomeValuesFrom",
            Self::ObjectAllValuesFrom => "ObjectAllValuesFrom",
            Self::ObjectHasValue => "ObjectHasValue",
            Self::ObjectHasSelf => "ObjectHasSelf",
            Self::ObjectMinCardinality => "ObjectMinCardinality",
            Self::ObjectMaxCardinality => "ObjectMaxCardinality",
            Self::ObjectExactCardinality => "ObjectExactCardinality",
            Self::DataSomeValuesFrom => "DataSomeValuesFrom",
            Self::DataAllValuesFrom => "DataAllValuesFrom",
            Self::DataHasValue => "DataHasValue",
            Self::DataMinCardinality => "DataMinCardinality",
            Self::DataMaxCardinality => "DataMaxCardinality",
            Self::DataExactCardinality => "DataExactCardinality",
            Self::DataComplementOf => "DataComplementOf",
            Self::DataOneOf => "DataOneOf",
            Self::DataIntersectionOf => "DataIntersectionOf",
            Self::DataUnionOf => "DataUnionOf",
            Self::DatatypeRestriction => "DatatypeRestriction",
            Self::FacetRestriction => "FacetRestriction",
            Self::SubClassOf => "SubClassOf",
            Self::EquivalentClasses => "EquivalentClasses",
            Self::DisjointClasses => "DisjointClasses",
            Self::DisjointUnion => "DisjointUnion",
            Self::SubObjectPropertyOf => "SubObjectPropertyOf",
            Self::ObjectPropertyChain => "ObjectPropertyChain",
            Self::EquivalentObjectProperties => "EquivalentObjectProperties",
            Self::DisjointObjectProperties => "DisjointObjectProperties",
            Self::InverseObjectProperties => "InverseObjectProperties",
            Self::ObjectPropertyDomain => "ObjectPropertyDomain",
            Self::ObjectPropertyRange => "ObjectPropertyRange",
            Self::FunctionalObjectProperty => "FunctionalObjectProperty",
            Self::InverseFunctionalObjectProperty => "InverseFunctionalObjectProperty",
            Self::SymmetricObjectProperty => "SymmetricObjectProperty",
            Self::AsymmetricObjectProperty => "AsymmetricObjectProperty",
            Self::ReflexiveObjectProperty => "ReflexiveObjectProperty",
            Self::IrreflexiveObjectProperty => "IrreflexiveObjectProperty",
            Self::TransitiveObjectProperty => "TransitiveObjectProperty",
            Self::SubDataPropertyOf => "SubDataPropertyOf",
            Self::EquivalentDataProperties => "EquivalentDataProperties",
            Self::DisjointDataProperties => "DisjointDataProperties",
            Self::DataPropertyDomain => "DataPropertyDomain",
            Self::DataPropertyRange => "DataPropertyRange",
            Self::FunctionalDataProperty => "FunctionalDataProperty",
            Self::SameIndividual => "SameIndividual",
            Self::DifferentIndividuals => "DifferentIndividuals",
            Self::ClassAssertion => "ClassAssertion",
            Self::ObjectPropertyAssertion => "ObjectPropertyAssertion",
            Self::DataPropertyAssertion => "DataPropertyAssertion",
            Self::NegativeObjectPropertyAssertion => "NegativeObjectPropertyAssertion",
            Self::NegativeDataPropertyAssertion => "NegativeDataPropertyAssertion",
            Self::AnnotationAssertion => "AnnotationAssertion",
            Self::SubAnnotationPropertyOf => "SubAnnotationPropertyOf",
            Self::AnnotationPropertyDomain => "AnnotationPropertyDomain",
            Self::AnnotationPropertyRange => "AnnotationPropertyRange",
            Self::Declaration => "Declaration",
            Self::HasKey => "HasKey",
            Self::DatatypeDefinition => "DatatypeDefinition",
            Self::Literal => "Literal",
            Self::IRI => "IRI",
            Self::AbbreviatedIRI => "AbbreviatedIRI",
            Self::Annotation => "Annotation",
            Self::Import => "Import",
            Self::Prefix => "Prefix",
            Self::Name => "name",
            Self::Cardinality => "cardinality",
            Self::NodeID => "nodeID",
            Self::AnnotationURI => "annotationURI",
            Self::DatatypeIRI => "datatypeIRI",
            Self::Facet => "facet",
            Self::DLSafeRule => "DLSafeRule",
            Self::Body => "Body",
            Self::Head => "Head",
            Self::ClassAtom => "ClassAtom",
            Self::DataRangeAtom => "DataRangeAtom",
            Self::ObjectPropertyAtom => "ObjectPropertyAtom",
            Self::DataPropertyAtom => "DataPropertyAtom",
            Self::BuiltInAtom => "BuiltInAtom",
            Self::SameIndividualAtom => "SameIndividualAtom",
            Self::DifferentIndividualsAtom => "DifferentIndividualsAtom",
            Self::Variable => "Variable",
            Self::DescriptionGraphRule => "DescriptionGraphRule",
        }
    }

    /// Get the full OWL/XML IRI for this element.
    #[must_use]
    pub fn iri(&self) -> IRI {
        IRI::new(&format!(
            "http://www.w3.org/2006/12/owl2-xml#{}",
            self.short_name()
        ))
    }
}
